# Generated by Django 2.2.6 on 2019-12-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('dates', models.DateField()),
                ('completed', models.IntegerField(default=0, verbose_name='completed')),
            ],
        ),
    ]
